<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net11.0;net11.0-browser</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <PackageId>Sia.Input</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sia" Version="2.1.2" />
  </ItemGroup>

</Project>
